version: '3.8'

services:
  cknn:
    build: .
    image: cknn-pytorch:latest
    container_name: cknn-anomaly-detection
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      # Mount data directories
      - ./features:/app/features
      - ./patches:/app/patches
      - ./meta:/app/meta
      # Mount output/results directory
      - ./results:/app/results
    working_dir: /app
    stdin_open: true
    tty: true
    shm_size: '8gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
